import type { Activity } from './types'

/**
 * The activity library: hand-written building blocks, not user data.
 * Rules of thumb used while writing it:
 *  - every firstStep is a single action that can be started inside a minute;
 *  - `equipment` lists only real extras (phone and shoes are assumed);
 *  - `weather: 'any'` means sheltered/indoor or genuinely weather-proof;
 *  - at least one activity is always valid (see `doorstep_reset`) so the engine can never come up empty.
 */
export const ACTIVITIES: Activity[] = [
  // ---------------------------------------------------------------- movement
  {
    id: 'brisk_walk_loop',
    title: 'Brisk walk, one familiar loop',
    family: 'movement',
    duration: { min: 15, max: 60, default: 30 },
    social: ['solo', 'with_friend'],
    needsOthers: false,
    intensity: 1,
    novelty: 1,
    cost: 'free',
    travel: 'none',
    equipment: [],
    weather: 'dry',
    daylight: 'any',
    tags: ['walking', 'walk'],
    motivators: ['calm', 'music'],
    bundles: ['podcast', 'music', 'audiobook', 'call'],
    firstStep: 'Put on your shoes, start something you enjoy listening to, and walk one loop you already know.',
  },
  {
    id: 'easy_jog',
    title: 'Easy jog at a conversational pace',
    family: 'movement',
    duration: { min: 15, max: 45, default: 25 },
    social: ['solo', 'with_friend'],
    needsOthers: false,
    intensity: 2,
    novelty: 1,
    cost: 'free',
    travel: 'none',
    equipment: [],
    weather: 'fair',
    daylight: 'any',
    tags: ['running', 'jogging', 'cardio'],
    motivators: ['mastery', 'music'],
    bundles: ['music', 'podcast'],
    firstStep: 'Lace up and jog the first two minutes slower than feels necessary.',
  },
  {
    id: 'stair_climb',
    title: 'Stair climb ladder',
    family: 'movement',
    duration: { min: 10, max: 25, default: 15 },
    social: ['solo', 'with_friend'],
    needsOthers: false,
    intensity: 3,
    novelty: 1,
    cost: 'free',
    travel: 'none',
    equipment: [],
    weather: 'any',
    daylight: 'any',
    tags: ['stairs', 'cardio', 'strength'],
    motivators: ['mastery', 'competition'],
    bundles: ['music'],
    firstStep: 'Walk to the nearest staircase and climb two floors at a steady pace.',
  },
  {
    id: 'cycling_ride',
    title: 'Easy bike ride',
    family: 'movement',
    duration: { min: 30, max: 120, default: 60 },
    social: ['solo', 'with_friend', 'small_group'],
    needsOthers: false,
    intensity: 2,
    novelty: 2,
    cost: 'free',
    travel: 'short',
    equipment: ['bicycle'],
    weather: 'fair',
    daylight: 'day',
    tags: ['cycling', 'biking', 'cardio'],
    motivators: ['exploration', 'music', 'nature'],
    bundles: ['music', 'podcast', 'photo'],
    firstStep: 'Check your tyres, fill a water bottle, and roll out to the end of your street.',
  },
  {
    id: 'badminton_game',
    title: 'Badminton game',
    family: 'movement',
    duration: { min: 40, max: 120, default: 60 },
    social: ['with_friend', 'small_group'],
    needsOthers: true,
    intensity: 2,
    novelty: 2,
    cost: 'low',
    travel: 'short',
    equipment: ['racket'],
    weather: 'any',
    daylight: 'any',
    tags: ['badminton', 'racket', 'sport'],
    motivators: ['social', 'competition', 'mastery'],
    bundles: ['photo'],
    firstStep: 'Message one friend: "Court in 30 minutes?" then pack your racket.',
  },
  {
    id: 'football_kickabout',
    title: 'Casual kickabout',
    family: 'movement',
    duration: { min: 40, max: 120, default: 60 },
    social: ['with_friend', 'small_group'],
    needsOthers: true,
    intensity: 2,
    novelty: 2,
    cost: 'free',
    travel: 'short',
    equipment: ['ball'],
    weather: 'dry',
    daylight: 'any',
    tags: ['football', 'soccer', 'ball', 'sport'],
    motivators: ['social', 'competition'],
    bundles: [],
    firstStep: 'Grab a ball and text two people: "Open ground, 20 minutes?"',
  },
  {
    id: 'swim_session',
    title: 'Pool swim',
    family: 'movement',
    duration: { min: 30, max: 75, default: 45 },
    social: ['solo', 'with_friend'],
    needsOthers: false,
    intensity: 2,
    novelty: 1,
    cost: 'low',
    travel: 'short',
    equipment: ['swimwear'],
    weather: 'any',
    daylight: 'day',
    tags: ['swimming', 'swim', 'cardio'],
    motivators: ['calm', 'mastery'],
    bundles: [],
    firstStep: 'Put your swimwear and a towel in a bag and head for the pool.',
  },
  {
    id: 'stretch_flow',
    title: 'Doorway stretch flow',
    family: 'movement',
    duration: { min: 10, max: 30, default: 15 },
    social: ['solo'],
    needsOthers: false,
    intensity: 1,
    novelty: 1,
    cost: 'free',
    travel: 'none',
    equipment: [],
    weather: 'any',
    daylight: 'any',
    tags: ['yoga', 'stretching', 'mobility'],
    motivators: ['calm'],
    bundles: ['music', 'podcast'],
    firstStep: 'Stand up, step away from the screen, and do five slow shoulder rolls.',
  },
  {
    id: 'bodyweight_park_circuit',
    title: 'Park bodyweight circuit',
    family: 'movement',
    duration: { min: 20, max: 40, default: 25 },
    social: ['solo', 'with_friend'],
    needsOthers: false,
    intensity: 3,
    novelty: 2,
    cost: 'free',
    travel: 'short',
    equipment: [],
    weather: 'fair',
    daylight: 'any',
    tags: ['strength', 'workout', 'bodyweight'],
    motivators: ['mastery', 'competition'],
    bundles: ['music'],
    firstStep: 'Walk to the nearest open space and do ten squats before you decide anything else.',
  },
  {
    id: 'living_room_dance',
    title: 'Three-song dance break',
    family: 'movement',
    duration: { min: 10, max: 30, default: 15 },
    social: ['solo', 'with_friend'],
    needsOthers: false,
    intensity: 2,
    novelty: 1,
    cost: 'free',
    travel: 'none',
    equipment: [],
    weather: 'any',
    daylight: 'any',
    tags: ['dance', 'music', 'cardio'],
    motivators: ['music', 'creativity'],
    bundles: ['music'],
    firstStep: 'Pick three songs you love, press play, and move until the third one ends.',
  },
  {
    id: 'doorstep_reset',
    title: 'Five-minute doorstep reset',
    family: 'movement',
    duration: { min: 5, max: 15, default: 5 },
    social: ['solo'],
    needsOthers: false,
    intensity: 1,
    novelty: 1,
    cost: 'free',
    travel: 'none',
    equipment: [],
    weather: 'any',
    daylight: 'any',
    tags: ['minimum', 'breathing', 'mindfulness'],
    motivators: ['calm'],
    bundles: [],
    firstStep: 'Open the door, step outside, and take ten slow breaths looking at something far away.',
  },

  // ------------------------------------------------------------- exploration
  {
    id: 'new_street_walk',
    title: 'Walk a street you have never walked',
    family: 'exploration',
    duration: { min: 20, max: 75, default: 40 },
    social: ['solo', 'with_friend'],
    needsOthers: false,
    intensity: 1,
    novelty: 3,
    cost: 'free',
    travel: 'short',
    equipment: [],
    weather: 'dry',
    daylight: 'day',
    tags: ['walking', 'exploring', 'neighbourhood'],
    motivators: ['novelty', 'exploration'],
    bundles: ['podcast', 'music', 'photo'],
    firstStep: 'Pick the turn you normally skip and walk down it for ten minutes.',
  },
  {
    id: 'sunset_spot_hunt',
    title: 'Hunt for the best sunset spot',
    family: 'exploration',
    duration: { min: 30, max: 75, default: 45 },
    social: ['solo', 'with_friend'],
    needsOthers: false,
    intensity: 1,
    novelty: 2,
    cost: 'free',
    travel: 'short',
    equipment: [],
    weather: 'dry',
    daylight: 'day',
    tags: ['photography', 'sunset', 'exploring'],
    motivators: ['exploration', 'calm', 'creativity'],
    bundles: ['photo', 'music'],
    firstStep: 'Head toward the highest open spot nearby and take the first photo when you get there.',
  },
  {
    id: 'photo_walk_challenge',
    title: 'Photo walk: five textures',
    family: 'exploration',
    duration: { min: 25, max: 75, default: 40 },
    social: ['solo', 'with_friend'],
    needsOthers: false,
    intensity: 1,
    novelty: 3,
    cost: 'free',
    travel: 'short',
    equipment: [],
    weather: 'dry',
    daylight: 'day',
    tags: ['photography', 'walking', 'challenge'],
    motivators: ['creativity', 'novelty', 'exploration'],
    bundles: ['photo', 'music'],
    firstStep: 'Walk out the door and photograph the first interesting texture you see: bark, brick, rust, water.',
  },
  {
    id: 'park_sit_and_watch',
    title: 'Sit in a park and watch for 15 minutes',
    family: 'exploration',
    duration: { min: 10, max: 40, default: 20 },
    social: ['solo', 'with_friend'],
    needsOthers: false,
    intensity: 1,
    novelty: 1,
    cost: 'free',
    travel: 'short',
    equipment: [],
    weather: 'dry',
    daylight: 'day',
    tags: ['park', 'mindfulness', 'nature'],
    motivators: ['calm', 'nature'],
    bundles: ['music', 'audiobook'],
    firstStep: 'Walk to the nearest bench or patch of shade and sit without opening your phone.',
  },
  {
    id: 'local_market_wander',
    title: 'Wander a local market',
    family: 'exploration',
    duration: { min: 30, max: 90, default: 45 },
    social: ['solo', 'with_friend', 'small_group'],
    needsOthers: false,
    intensity: 1,
    novelty: 2,
    cost: 'low',
    travel: 'short',
    equipment: [],
    weather: 'any',
    daylight: 'day',
    tags: ['market', 'food', 'walking', 'exploring'],
    motivators: ['exploration', 'food', 'novelty'],
    bundles: ['photo'],
    firstStep: 'Head to the nearest market and try one thing you have never bought before.',
  },
  {
    id: 'new_cafe_walk',
    title: 'Walk to a tea stall or cafe you have not tried',
    family: 'exploration',
    duration: { min: 30, max: 90, default: 50 },
    social: ['solo', 'with_friend'],
    needsOthers: false,
    intensity: 1,
    novelty: 2,
    cost: 'low',
    travel: 'short',
    equipment: [],
    weather: 'dry',
    daylight: 'any',
    tags: ['cafe', 'food', 'walking', 'exploring'],
    motivators: ['food', 'exploration', 'social'],
    bundles: ['podcast', 'music', 'call'],
    firstStep: 'Choose a place you have never been, put it in your maps app, and start walking there.',
  },
  {
    id: 'nature_trail_hike',
    title: 'Half-day nature trail',
    family: 'exploration',
    duration: { min: 90, max: 300, default: 150 },
    social: ['solo', 'with_friend', 'small_group'],
    needsOthers: false,
    intensity: 3,
    novelty: 3,
    cost: 'low',
    travel: 'far',
    equipment: [],
    weather: 'fair',
    daylight: 'day',
    tags: ['hiking', 'trail', 'nature'],
    motivators: ['nature', 'exploration', 'novelty'],
    bundles: ['photo', 'music', 'podcast'],
    firstStep: 'Choose a trailhead within reach, fill two bottles of water, and set off.',
  },
  {
    id: 'waterfront_walk',
    title: 'Walk along water',
    family: 'exploration',
    duration: { min: 30, max: 90, default: 50 },
    social: ['solo', 'with_friend'],
    needsOthers: false,
    intensity: 1,
    novelty: 2,
    cost: 'free',
    travel: 'short',
    equipment: [],
    weather: 'dry',
    daylight: 'day',
    tags: ['walking', 'nature', 'waterfront', 'photography'],
    motivators: ['calm', 'nature', 'exploration'],
    bundles: ['photo', 'podcast', 'music'],
    firstStep: 'Go to the nearest lake, river or shoreline and walk along it for the first ten minutes.',
  },
  {
    id: 'neighbourhood_scavenger_hunt',
    title: 'Neighbourhood scavenger hunt',
    family: 'exploration',
    duration: { min: 25, max: 75, default: 40 },
    social: ['solo', 'with_friend', 'small_group'],
    needsOthers: false,
    intensity: 1,
    novelty: 3,
    cost: 'free',
    travel: 'short',
    equipment: [],
    weather: 'dry',
    daylight: 'day',
    tags: ['scavenger', 'exploring', 'challenge', 'photography'],
    motivators: ['novelty', 'exploration', 'competition'],
    bundles: ['photo'],
    firstStep: 'Write a list of five things to find (a red door, a mural, a sundial...) and walk out to find the first.',
  },
  {
    id: 'rooftop_stargazing',
    title: 'Stargazing from an open space',
    family: 'exploration',
    duration: { min: 20, max: 60, default: 30 },
    social: ['solo', 'with_friend'],
    needsOthers: false,
    intensity: 1,
    novelty: 2,
    cost: 'free',
    travel: 'short',
    equipment: [],
    weather: 'clear_sky',
    daylight: 'night',
    tags: ['stargazing', 'nature', 'night'],
    motivators: ['calm', 'nature', 'novelty'],
    bundles: ['music', 'photo'],
    firstStep: 'Switch off nearby lights, go to the most open spot you can reach safely, and let your eyes adjust for five minutes.',
  },
  {
    id: 'barefoot_grass_break',
    title: 'Literally touch grass',
    family: 'exploration',
    duration: { min: 5, max: 30, default: 10 },
    social: ['solo', 'with_friend'],
    needsOthers: false,
    intensity: 1,
    novelty: 1,
    cost: 'free',
    travel: 'short',
    equipment: [],
    weather: 'dry',
    daylight: 'day',
    tags: ['grass', 'barefoot', 'mindfulness', 'nature'],
    motivators: ['calm', 'nature'],
    bundles: [],
    firstStep: 'Walk to the nearest patch of grass, take your shoes off, and stand there for one full minute.',
  },

  // ------------------------------------------------------------ social_skill
  {
    id: 'call_friend_walk',
    title: 'Walk while catching up with a friend by phone',
    family: 'social_skill',
    duration: { min: 20, max: 60, default: 35 },
    social: ['solo'],
    needsOthers: false,
    intensity: 1,
    novelty: 1,
    cost: 'free',
    travel: 'none',
    equipment: [],
    weather: 'dry',
    daylight: 'any',
    tags: ['walking', 'call', 'friends'],
    motivators: ['social'],
    bundles: ['call'],
    firstStep: 'Call someone you have been meaning to talk to, and start walking while it rings.',
  },
  {
    id: 'walk_and_talk',
    title: 'Walk and talk with a friend',
    family: 'social_skill',
    duration: { min: 25, max: 75, default: 45 },
    social: ['with_friend', 'small_group'],
    needsOthers: true,
    intensity: 1,
    novelty: 1,
    cost: 'free',
    travel: 'none',
    equipment: [],
    weather: 'dry',
    daylight: 'any',
    tags: ['walking', 'friends', 'talk'],
    motivators: ['social', 'calm'],
    bundles: [],
    firstStep: 'Message a friend: "Walk for 30 minutes? I will come to you."',
  },
  {
    id: 'outdoor_sketching',
    title: 'Sketch what you can see',
    family: 'social_skill',
    duration: { min: 20, max: 75, default: 40 },
    social: ['solo', 'with_friend'],
    needsOthers: false,
    intensity: 1,
    novelty: 2,
    cost: 'free',
    travel: 'short',
    equipment: ['sketchbook'],
    weather: 'dry',
    daylight: 'day',
    tags: ['drawing', 'sketching', 'art', 'creative'],
    motivators: ['creativity', 'mastery', 'calm'],
    bundles: ['music', 'podcast'],
    firstStep: 'Put your sketchbook and a pen in your bag and sit at the first spot with a view you like.',
  },
  {
    id: 'ball_skills_practice',
    title: 'Ball skills practice',
    family: 'social_skill',
    duration: { min: 15, max: 45, default: 25 },
    social: ['solo', 'with_friend'],
    needsOthers: false,
    intensity: 2,
    novelty: 1,
    cost: 'free',
    travel: 'short',
    equipment: ['ball'],
    weather: 'dry',
    daylight: 'any',
    tags: ['ball', 'skill', 'football', 'practice'],
    motivators: ['mastery', 'music'],
    bundles: ['music'],
    firstStep: 'Take a ball to the nearest open space and try the same trick ten times in a row.',
  },
  {
    id: 'basketball_shootaround',
    title: 'Basketball shootaround',
    family: 'social_skill',
    duration: { min: 20, max: 75, default: 35 },
    social: ['solo', 'with_friend', 'small_group'],
    needsOthers: false,
    intensity: 2,
    novelty: 1,
    cost: 'free',
    travel: 'short',
    equipment: ['ball'],
    weather: 'dry',
    daylight: 'any',
    tags: ['basketball', 'ball', 'sport', 'skill'],
    motivators: ['mastery', 'competition', 'social'],
    bundles: ['music'],
    firstStep: 'Take your ball to the nearest court and take your first ten shots.',
  },
  {
    id: 'picnic_with_friend',
    title: 'Simple picnic',
    family: 'social_skill',
    duration: { min: 45, max: 150, default: 75 },
    social: ['with_friend', 'small_group'],
    needsOthers: true,
    intensity: 1,
    novelty: 2,
    cost: 'low',
    travel: 'short',
    equipment: [],
    weather: 'fair',
    daylight: 'day',
    tags: ['picnic', 'food', 'friends', 'park'],
    motivators: ['social', 'food', 'calm'],
    bundles: ['music', 'photo'],
    firstStep: 'Text a friend "Picnic?", then put one snack and one drink in a bag.',
  },
  {
    id: 'litter_pick_walk',
    title: 'Litter-pick walk',
    family: 'social_skill',
    duration: { min: 20, max: 60, default: 30 },
    social: ['solo', 'with_friend', 'small_group'],
    needsOthers: false,
    intensity: 1,
    novelty: 2,
    cost: 'free',
    travel: 'short',
    equipment: ['trash_bag'],
    weather: 'dry',
    daylight: 'day',
    tags: ['volunteering', 'cleanup', 'nature', 'walking'],
    motivators: ['purpose', 'nature', 'social'],
    bundles: ['podcast', 'music'],
    firstStep: 'Take a bag and gloves, and fill it from one park or street you care about.',
  },
  {
    id: 'cards_outside',
    title: 'Card or board game outside',
    family: 'social_skill',
    duration: { min: 40, max: 150, default: 60 },
    social: ['with_friend', 'small_group'],
    needsOthers: true,
    intensity: 1,
    novelty: 2,
    cost: 'free',
    travel: 'none',
    equipment: ['cards'],
    weather: 'any',
    daylight: 'any',
    tags: ['games', 'cards', 'friends'],
    motivators: ['social', 'competition'],
    bundles: ['music'],
    firstStep: 'Grab a deck of cards and invite someone to a table or balcony.',
  },
]

const BY_ID = new Map(ACTIVITIES.map((a) => [a.id, a]))

export function getActivity(id: string): Activity | undefined {
  return BY_ID.get(id)
}

/** The activity that is valid for almost anyone, almost anywhere, at any time. */
export const GUARANTEED_FALLBACK_ID = 'doorstep_reset'
