import { z } from 'zod'
import { locationSchema, type ConditionsSummary } from './context'
import { getActivity } from './engine/activities'
import type { LearnedItem } from './learned'
import type { MeadowSummary, Milestone, RewardSummary } from './meadow'
import { NOTE_MAX, type MemoryItem, type MissionRecord } from './mission-record'
import type { FlowStat, ValueMetrics } from './metrics'
import type { NextStep, PlanPrefill } from './next-step'
import {
  ACTIVITY_MODES,
  DESIRED_OUTCOMES,
  FEELINGS,
  GOALS,
  HELPERS,
  WOULD_REPEAT,
  AVOIDANCES,
  EQUIPMENT,
  MOODS,
  MOTIVATORS,
  OUTCOMES,
  SKIP_REASONS,
  SOCIAL_PREFERENCES,
  type Outcome,
  type Recommendation,
  type SkipReason,
  type UserProfile,
} from './engine/types'

/** Request/response contract shared by the Worker (validation) and the React app (types). */

// ---------------------------------------------------------------- primitives

/** Anonymous session id, generated by the browser (crypto.randomUUID) and sent as `X-Session-Id`. */
export const sessionIdSchema = z.uuid()

/** Free-text interest/dislike: normalised so "Running " and "running" are the same term. */
const term = z.string().trim().toLowerCase().min(1).max(40)
const termList = z
  .array(term)
  .max(30)
  .transform((xs) => [...new Set(xs)])

/** "17:30-19:30" */
const timeWindow = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d-([01]\d|2[0-3]):[0-5]\d$/, 'expected HH:MM-HH:MM')

const uniq = <T extends z.ZodType>(item: T) => z.array(item).max(32).transform((xs) => [...new Set(xs)])

// ---------------------------------------------------------------- profile

export const preferencesSchema = z.strictObject({
  likes: termList,
  dislikes: termList,
  preferred_duration_min: z.int().min(5).max(300),
  social_preference: z.enum(SOCIAL_PREFERENCES),
})

// Plain lists first: a PATCH must be able to leave them out WITHOUT the default turning "absent" into "empty".
const goalList = uniq(z.enum(GOALS))
const windowList = z.array(timeWindow).max(4)

/** A list of real activity ids (the person's "never suggest this" list). */
const activityIdList = z
  .array(z.string().refine((id) => getActivity(id) !== undefined, 'unknown activity'))
  .max(40)
  .transform((xs) => [...new Set(xs)])

export const profileInputSchema = z.strictObject({
  preferences: preferencesSchema,
  motivators: uniq(z.enum(MOTIVATORS)),
  avoidances: uniq(z.enum(AVOIDANCES)),
  equipment: uniq(z.enum(EQUIPMENT)),
  /** Optional: what the person wants out of this. Older profiles simply have none. */
  goals: goalList.default([]),
  best_windows: windowList.default([]),
  /** Activities they asked never to see again. Optional: saving preferences keeps what is already there. */
  avoid_activities: activityIdList.optional(),
})
export type ProfileInput = z.infer<typeof profileInputSchema>

export const profilePatchSchema = z.strictObject({
  preferences: preferencesSchema.partial().optional(),
  motivators: profileInputSchema.shape.motivators.optional(),
  avoidances: profileInputSchema.shape.avoidances.optional(),
  equipment: profileInputSchema.shape.equipment.optional(),
  goals: goalList.optional(),
  best_windows: windowList.optional(),
  avoid_activities: activityIdList.optional(),
})
export type ProfilePatch = z.infer<typeof profilePatchSchema>

/** What we store and return: the engine's profile plus schedule hints. */
/** The person's say over what the assistant has learned. Stored with the profile; the patterns themselves are recomputed. */
export interface LearningControls {
  /** Pattern ids they said are not true for them: never used, never shown again until restored. */
  dismissed: string[]
  /** Patterns they confirmed, with the wording and day they confirmed it (they become "lessons" in the meadow). */
  confirmed: { id: string; text: string; at: string }[]
  /** Answers before this moment (UTC) are ignored by learning: "start again from scratch". */
  reset_at?: string
}

export interface StoredProfile extends Omit<UserProfile, 'user_id'> {
  schedule_signals: { best_windows: string[] }
  updated_at: string
  learning?: LearningControls
}

export interface ProfileStats {
  recommendations: number
  responded: number
  completed: number
  /** completed / responded, or null until there is any feedback. */
  completion_rate: number | null
}

export interface ProfileResponse {
  profile: StoredProfile
  stats: ProfileStats
  /** Which flow this person has: the Mission Companion (everyone, unless an experiment is switched on) or the earlier plain one. */
  flow: Flow
}

export type Flow = 'companion' | 'classic'

/** GET /api/profile: "no profile yet" is a normal 200 answer (so a first visit logs no error), not a 404. */
export type ProfileLookupResponse = ProfileResponse | { profile: null }

// ---------------------------------------------------------------- recommend

export const recommendInputSchema = z.strictObject({
  duration_limit: z.int().min(5).max(480),
  mood: z.enum(MOODS).default('ok'),
  social_available: z.boolean().default(false),
  /** Minutes east of UTC for the user's clock (browser: -new Date().getTimezoneOffset()). */
  utc_offset_minutes: z.int().min(-840).max(840).optional(),
  /** Set false to skip the AI and get the instant deterministic pick (also saves the free daily AI quota). */
  use_ai: z.boolean().default(true),
  /**
   * How big today's activity should be. 'auto' (default) lets the engine decide from energy and recent history
   * (e.g. a small one after two skips); otherwise the person's choice is used as is.
   */
  mode: z.enum(['auto', ...ACTIVITY_MODES]).default('auto'),
  /**
   * Optional, and only ever sent with the person's consent. Used to look up live weather and daylight, rounded to
   * ~1 km, and NEVER stored. Without it the recommendation is made without weather.
   */
  location: locationSchema.optional(),
  /**
   * Last-known profile, kept in the person's own browser. Used ONLY if saved data cannot be read right now, so a
   * database outage still gives a real recommendation (without history, and without saving it).
   */
  fallback_profile: profileInputSchema.optional(),
  /** What they want out of this one (the check-in). Optional: asking is adaptive. */
  desired_outcome: z.enum(DESIRED_OUTCOMES).optional(),
})
export type RecommendInput = z.input<typeof recommendInputSchema>

export interface RecommendResponse extends Recommendation {
  recommendation_id: string
  /** False if saving the event failed; the recommendation is still valid, feedback may not be recordable. */
  persisted: boolean
  /** The live conditions this recommendation was made with. Absent when no location was given or weather was unavailable. */
  context?: ConditionsSummary
  /** Which flow this person has. */
  flow?: Flow
}

// ----------------------------------------------------------------- upgrade

export const recommendationIdSchema = z.string().regex(/^r_[0-9a-f-]{36}$/, 'invalid recommendation id')

/**
 * Result of asking the AI to improve a recommendation that was already shown.
 * `upgraded: false` is a normal, successful answer: the screen simply keeps what it has.
 */
export interface UpgradeResponse {
  upgraded: boolean
  /** Why nothing changed. Only present when `upgraded` is false. */
  reason?: 'ai_unavailable' | 'ai_cooling_down' | 'already_attempted' | 'ai_failed'
  /** The improved recommendation (same `recommendation_id`). Only present when `upgraded` is true. */
  recommendation?: RecommendResponse
}

// ---------------------------------------------------------------- feedback

export const feedbackInputSchema = z
  .strictObject({
    recommendation_id: z.string().regex(/^r_[0-9a-f-]{36}$/, 'invalid recommendation id'),
    outcome: z.enum(OUTCOMES),
    enjoyment: z.int().min(1).max(5).optional(),
    skip_reason: z.enum(SKIP_REASONS).optional(),
    /** Minutes away from the app (measured from "Let's go" to "I am back", or what the person said). */
    minutes_outside: z.int().min(0).max(480).optional(),
    /** Whether they tried the optional prompt (1) or not (0). */
    quests_done: z.int().min(0).max(3).optional(),
    /** How they feel now compared with before. */
    feeling: z.enum(FEELINGS).optional(),
    /** What made it easier. */
    helper: z.enum(HELPERS).optional(),
    /** What made it harder (same vocabulary as skip reasons). */
    barrier: z.enum(SKIP_REASONS).optional(),
    would_repeat: z.enum(WOULD_REPEAT).optional(),
    /** Their own words: the memory. Plain text only. */
    note: z
      .string()
      .trim()
      .max(NOTE_MAX)
      .refine((t) => !/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(t), 'control characters are not allowed')
      .optional(),
    /** True if they kept a photo. It stays on their device; only this flag comes to us. */
    has_photo: z.boolean().optional(),
    /** Were the minutes measured by the app, or typed in by the person? */
    minutes_source: z.enum(['measured', 'stated']).optional(),
    /** When they set off (ISO, from their device). */
    started_at: z.iso.datetime({ offset: true }).optional(),
  })
  .superRefine((v, ctx) => {
    const credited = v.outcome === 'completed' || v.outcome === 'partial'
    for (const key of ['minutes_outside', 'quests_done', 'feeling', 'helper', 'barrier', 'would_repeat', 'note', 'has_photo', 'minutes_source', 'started_at'] as const) {
      if (v[key] !== undefined && !credited) ctx.addIssue({ code: 'custom', path: [key], message: `${key} only applies to completed or partial` })
    }
    if (v.enjoyment !== undefined && v.outcome !== 'completed' && v.outcome !== 'partial') {
      ctx.addIssue({ code: 'custom', path: ['enjoyment'], message: 'enjoyment only applies to completed or partial' })
    }
    if (v.skip_reason !== undefined && v.outcome !== 'skipped' && v.outcome !== 'changed') {
      ctx.addIssue({ code: 'custom', path: ['skip_reason'], message: 'skip_reason only applies to skipped or changed' })
    }
  })
export type FeedbackInput = z.input<typeof feedbackInputSchema>

export interface FeedbackResponse {
  recommendation_id: string
  outcome: Outcome
  enjoyment: number | null
  skip_reason: SkipReason | null
  /** Present for completed or partial missions: what this one added to the meadow. */
  reward?: RewardSummary
  /** Plain sentences saying what will be done differently because of these answers. */
  adaptations: string[]
  /** When it did not happen: honesty is recognised (a seed in the meadow). It adds no time, and nothing is taken away. */
  recognition?: { seeds: number; new_milestones: Milestone[] }
  /** When it did not happen: a smaller next step to try, never a dead end. */
  next_step?: NextStep
  /** When they said they would not repeat it: offer to stop suggesting it altogether. */
  ask_to_avoid?: { activity_id: string; title: string }
}

// ---------------------------------------------------------------- meadow

export const meadowQuerySchema = z.object({
  /** Minutes east of UTC for the person's clock, so "this week" starts and ends in their own time. */
  utc_offset_minutes: z.coerce.number().int().min(-840).max(840).optional(),
})

export type MeadowResponse = MeadowSummary

// ---------------------------------------------------------------- history

export const historyQuerySchema = z.object({
  limit: z.coerce.number().int().min(1).max(100).default(20),
})

export interface HistoryItem {
  recommendation_id: string
  timestamp: string
  activity_id: string
  title: string
  outcome: Outcome | 'pending'
  enjoyment: number | null
  skip_reason: SkipReason | null
}

export interface HistoryResponse {
  items: HistoryItem[]
}

// ---------------------------------------------------------------- errors

export interface ApiErrorBody {
  error: {
    code: string
    message: string
    details?: { path: string; message: string }[]
  }
}

// ------------------------------------------------------- what was learned

export const learnedRespondSchema = z.strictObject({
  id: z.string().min(3).max(80),
  action: z.enum(['confirm', 'dismiss', 'restore']),
})

export interface LearnedView extends LearnedItem {
  /** What the person has done with it: nothing yet, confirmed it, or said it is not true. */
  status: 'active' | 'confirmed' | 'dismissed'
}

export interface LearnedResponse {
  items: LearnedView[]
  /** Patterns the person confirmed (kept even if the answers change). */
  lessons: { id: string; text: string; at: string }[]
  /** Activities they asked never to see again. */
  avoid: { activity_id: string; title: string }[]
  /** When they last started learning from scratch, if ever. */
  reset_at: string | null
  /** What this is, how it is used, and what they can do about it. */
  explanation: string
  /** Something kind the assistant noticed that fits right now, with a one-tap way to try it. */
  suggestion: { text: string; plan: PlanPrefill } | null
}

// ------------------------------------------------------------ memories

export const memoriesQuerySchema = z.object({ limit: z.coerce.number().int().min(1).max(200).default(60) })

/** Correct or remove a memory: any field set to null is cleared. */
export const memoryPatchSchema = z
  .strictObject({
    note: z
      .string()
      .trim()
      .max(NOTE_MAX)
      .refine((t) => !/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(t), 'control characters are not allowed')
      .nullable()
      .optional(),
    feeling: z.enum(FEELINGS).nullable().optional(),
    would_repeat: z.enum(WOULD_REPEAT).nullable().optional(),
    has_photo: z.boolean().optional(),
  })
  .refine((v) => Object.keys(v).length > 0, 'nothing to change')

export interface MemoriesResponse {
  items: MemoryItem[]
}

export interface MemoryResponse {
  item: MemoryItem
}

// ------------------------------------------------------------- records, metrics

export interface MissionsResponse {
  records: MissionRecord[]
}

export interface MetricsResponse {
  metrics: ValueMetrics
  /** Plain-language lines that the numbers support. */
  lines: string[]
}

export interface ExperimentResponse {
  /** Percent of people in the plain (classic) arm. 0 means everyone has the Mission Companion. */
  classic_percent: number
  arms: FlowStat[]
}
