import { z } from 'zod'
import {
  AVOIDANCES,
  EQUIPMENT,
  MOODS,
  MOTIVATORS,
  OUTCOMES,
  SKIP_REASONS,
  SOCIAL_PREFERENCES,
  type Outcome,
  type Recommendation,
  type SkipReason,
  type UserProfile,
} from './engine/types'

/** Request/response contract shared by the Worker (validation) and the React app (types). */

// ---------------------------------------------------------------- primitives

/** Anonymous session id, generated by the browser (crypto.randomUUID) and sent as `X-Session-Id`. */
export const sessionIdSchema = z.uuid()

/** Free-text interest/dislike: normalised so "Running " and "running" are the same term. */
const term = z.string().trim().toLowerCase().min(1).max(40)
const termList = z
  .array(term)
  .max(30)
  .transform((xs) => [...new Set(xs)])

/** "17:30-19:30" */
const timeWindow = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d-([01]\d|2[0-3]):[0-5]\d$/, 'expected HH:MM-HH:MM')

const uniq = <T extends z.ZodType>(item: T) => z.array(item).max(32).transform((xs) => [...new Set(xs)])

// ---------------------------------------------------------------- profile

export const preferencesSchema = z.strictObject({
  likes: termList,
  dislikes: termList,
  preferred_duration_min: z.int().min(5).max(300),
  social_preference: z.enum(SOCIAL_PREFERENCES),
})

export const profileInputSchema = z.strictObject({
  preferences: preferencesSchema,
  motivators: uniq(z.enum(MOTIVATORS)),
  avoidances: uniq(z.enum(AVOIDANCES)),
  equipment: uniq(z.enum(EQUIPMENT)),
  best_windows: z.array(timeWindow).max(4).default([]),
})
export type ProfileInput = z.infer<typeof profileInputSchema>

export const profilePatchSchema = z.strictObject({
  preferences: preferencesSchema.partial().optional(),
  motivators: profileInputSchema.shape.motivators.optional(),
  avoidances: profileInputSchema.shape.avoidances.optional(),
  equipment: profileInputSchema.shape.equipment.optional(),
  best_windows: profileInputSchema.shape.best_windows.optional(),
})
export type ProfilePatch = z.infer<typeof profilePatchSchema>

/** What we store and return: the engine's profile plus schedule hints. */
export interface StoredProfile extends Omit<UserProfile, 'user_id'> {
  schedule_signals: { best_windows: string[] }
  updated_at: string
}

export interface ProfileStats {
  recommendations: number
  responded: number
  completed: number
  /** completed / responded, or null until there is any feedback. */
  completion_rate: number | null
}

export interface ProfileResponse {
  profile: StoredProfile
  stats: ProfileStats
}

// ---------------------------------------------------------------- recommend

export const recommendInputSchema = z.strictObject({
  duration_limit: z.int().min(5).max(480),
  mood: z.enum(MOODS).default('ok'),
  social_available: z.boolean().default(false),
  /** Minutes east of UTC for the user's clock (browser: -new Date().getTimezoneOffset()). */
  utc_offset_minutes: z.int().min(-840).max(840).optional(),
  /** Set false to skip the AI and get the instant deterministic pick (also saves the free daily AI quota). */
  use_ai: z.boolean().default(true),
})
export type RecommendInput = z.input<typeof recommendInputSchema>

export interface RecommendResponse extends Recommendation {
  recommendation_id: string
  /** False if saving the event failed; the recommendation is still valid, feedback may not be recordable. */
  persisted: boolean
}

// ----------------------------------------------------------------- upgrade

export const recommendationIdSchema = z.string().regex(/^r_[0-9a-f-]{36}$/, 'invalid recommendation id')

/**
 * Result of asking the AI to improve a recommendation that was already shown.
 * `upgraded: false` is a normal, successful answer: the screen simply keeps what it has.
 */
export interface UpgradeResponse {
  upgraded: boolean
  /** Why nothing changed. Only present when `upgraded` is false. */
  reason?: 'ai_unavailable' | 'ai_cooling_down' | 'already_attempted' | 'ai_failed'
  /** The improved recommendation (same `recommendation_id`). Only present when `upgraded` is true. */
  recommendation?: RecommendResponse
}

// ---------------------------------------------------------------- feedback

export const feedbackInputSchema = z
  .strictObject({
    recommendation_id: z.string().regex(/^r_[0-9a-f-]{36}$/, 'invalid recommendation id'),
    outcome: z.enum(OUTCOMES),
    enjoyment: z.int().min(1).max(5).optional(),
    skip_reason: z.enum(SKIP_REASONS).optional(),
  })
  .superRefine((v, ctx) => {
    if (v.enjoyment !== undefined && v.outcome !== 'completed' && v.outcome !== 'partial') {
      ctx.addIssue({ code: 'custom', path: ['enjoyment'], message: 'enjoyment only applies to completed or partial' })
    }
    if (v.skip_reason !== undefined && v.outcome !== 'skipped' && v.outcome !== 'changed') {
      ctx.addIssue({ code: 'custom', path: ['skip_reason'], message: 'skip_reason only applies to skipped or changed' })
    }
  })
export type FeedbackInput = z.input<typeof feedbackInputSchema>

export interface FeedbackResponse {
  recommendation_id: string
  outcome: Outcome
  enjoyment: number | null
  skip_reason: SkipReason | null
}

// ---------------------------------------------------------------- history

export const historyQuerySchema = z.object({
  limit: z.coerce.number().int().min(1).max(100).default(20),
})

export interface HistoryItem {
  recommendation_id: string
  timestamp: string
  activity_id: string
  title: string
  outcome: Outcome | 'pending'
  enjoyment: number | null
  skip_reason: SkipReason | null
}

export interface HistoryResponse {
  items: HistoryItem[]
}

// ---------------------------------------------------------------- errors

export interface ApiErrorBody {
  error: {
    code: string
    message: string
    details?: { path: string; message: string }[]
  }
}
